# Generated by Django 2.2.5 on 2019-11-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='id',
        ),
        migrations.AlterField(
            model_name='journey',
            name='avatar_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journey',
            name='event',
            field=models.CharField(default='{}', max_length=512),
        ),
    ]
