# Generated by Django 2.2.5 on 2019-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0002_auto_20191101_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='avatar_id',
            field=models.CharField(default='0', max_length=128, primary_key=True, serialize=False),
        ),
    ]
