# Generated by Django 2.2.5 on 2019-11-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0004_auto_20191105_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='event',
            field=models.CharField(default='', max_length=512),
        ),
    ]
