# Generated by Django 2.2.5 on 2019-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0005_auto_20191105_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='difficulty',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
