# Generated by Django 2.2.5 on 2019-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0008_auto_20191111_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='event_queue',
            field=models.CharField(default='[]', max_length=512),
        ),
    ]
