# Generated by Django 2.2.5 on 2019-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0009_auto_20191111_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='event_queue',
            field=models.CharField(default='[]', max_length=1024),
        ),
    ]
