# Generated by Django 2.2.5 on 2019-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0010_auto_20191111_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='current_event',
        ),
    ]
