# Generated by Django 2.2.5 on 2019-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0011_remove_journey_current_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='event_current',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
