# Generated by Django 2.2.5 on 2019-11-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0012_journey_event_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='map_level',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='journey',
            name='map_user',
            field=models.TextField(default='[]'),
        ),
    ]
