# Generated by Django 2.2.5 on 2019-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Citadel', '0013_auto_20191121_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='event_current',
            field=models.CharField(default='{}', max_length=1024),
        ),
    ]
