# Generated by Django 2.2.5 on 2019-10-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('attack', models.CharField(default='0', max_length=128)),
                ('defense', models.CharField(default='0', max_length=128)),
                ('speed', models.CharField(default='0', max_length=128)),
                ('range', models.CharField(default='0', max_length=128)),
                ('magic', models.CharField(default='0', max_length=128)),
                ('comments', models.TextField(default='')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-c_time'],
            },
        ),
    ]
