# Generated by Django 2.2.5 on 2019-10-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Avatar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='hostId',
            new_name='user_id',
        ),
    ]
