# Generated by Django 2.2.5 on 2019-12-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aeon_Avatar', '0003_auto_20191101_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='magic',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='range',
        ),
    ]
